using Microsoft.AspNetCore.Mvc;

// BlogController handles HTTP requests for Blog resources.
//
// ARCHITECTURE CHECK: this file imports ONLY Microsoft.AspNetCore.Mvc.
// There is NO MongoDB.Driver import here — that is intentional and required.
// The controller depends on IBlogRepository (the interface), not on any specific
// database implementation. This is the Repository Pattern working correctly.
// If we swap MongoDB for PostgreSQL, this file does not change at all.
[ApiController]
[Route("api/blogs")]
public class BlogController : ControllerBase
{
    private readonly IBlogRepository _blogs;

    // IBlogRepository is injected by the DI container (registered in Program.cs).
    // The controller doesn't know or care whether it's Mongo, Postgres, or an in-memory fake.
    public BlogController(IBlogRepository blogs)
    {
        _blogs = blogs;
    }

    // GET /api/blogs/{id}
    // Returns the blog AND all its posts via BlogWithPostsDto.
    // Posts are fetched from a separate collection and joined in the repository.
    [HttpGet("{id}")]
    public async Task<IActionResult> GetById(string id)
    {
        var blog = await _blogs.GetById(id);
        if (blog is null) return NotFound();
        return Ok(blog);
    }

    // GET /api/blogs
    // Returns all blogs (metadata only, no posts attached).
    [HttpGet]
    public async Task<IActionResult> GetAll()
    {
        var blogs = await _blogs.GetAll();
        return Ok(blogs);
    }

    // POST /api/blogs
    // Creates a new blog. Returns 201 Created with the created resource and a Location header.
    // The Id is generated by MongoDB — it is null in the request body and populated after insert.
    [HttpPost]
    public async Task<IActionResult> Create(Blog blog)
    {
        var created = await _blogs.Create(blog);
        return CreatedAtAction(nameof(GetById), new { id = created.Id }, created);
    }

    // DELETE /api/blogs/{id}
    // Deletes the blog AND all its posts (cascaded manually in the repository).
    // MongoDB has no cascading deletes — the repository handles this explicitly.
    [HttpDelete("{id}")]
    public async Task<IActionResult> Delete(string id)
    {
        await _blogs.Delete(id);
        return NoContent();  // 204 — success, no body
    }
}
